In [2]:
%matplotlib inline
from collections import Counter
import random

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
train_data=pd.read_json('data/train.json',lines=True)
test_data=pd.read_json('data/test.json',lines=True)

In [4]:
train_data.dropna()
train_data

code  \
0                         protected void tearDown(){\n}\n   
1       @KnownFailure("Fixed on DonutBurger, Wrong Exc...   
2       public static CstFloat make(int bits){\n  retu...   
3       public long size(){\n  long size=0;\n  if (par...   
4       public void increment(View view){\n  if (quant...   
5       public void trimToSize(){\n  ++modCount;\n  if...   
6       public SyncValueResponseMessage(SyncValueRespo...   
7       public void clearParsers(){\n  if (parserManag...   
8       @Override public void run(){\n  while (doWork)...   
9       private byte[] calculateUValue(byte[] generalK...   
10      private void assign(HashMap<String,DBIDs> labe...   
11      private void showFeedback(String message){\n  ...   
12      public CDeleteAction(final BackEndDebuggerProv...   
13      public Yaml(BaseConstructor constructor,Repres...   
14      public void testHitEndAfterFind(){\n  hitEndTe...   
15      public void add(Individual individual){\n  ind...   
16      public boolean removeSession(IgniteUuid sesId)...   
17      public static Bitmap loadBitmapOptimized(Uri u...   
18      protected BasePeriod(long duration){\n  super(...   
19        public FlatBufferBuilder(){\n  this(1024);\n}\n   
20      public PbrpcConnectionException(String arg0,Th...   
21      public void uninstallUI(JComponent a){\n  for ...   
22      public static void shutdown(){\n  if (instance...   
23      public boolean GE(Word w2){\n  return value.GE...   
24      public static UnionCoder of(List<Coder<?>> ele...   
25      public void testFileDeletion() throws Exceptio...   
26      public boolean isOnClasspath(String classpath)...   
27      protected void source(String ceylon){\n  Strin...   
28      public PerformanceMonitor(){\n  initComponents...   
29      @DSGenerator(tool_name="Doppelganger",tool_ver...   
...                                                   ...   
470456  int[] decodeStart(BitArray row) throws NotFoun...   
470457  public static boolean contains(int[] array,int...   
470458  public static double acosh(final double value)...   
470459  public void fireDataStatusEEvent(String AD_Mes...   
470460  AttributeDefinition(TextAttributeSet attrs,int...   
470461  public void consumeGreedy(String greedyToken){...   
470462  public static int hexToDecimal(String hex) thr...   
470463  @Override public Result decode(BinaryBitmap im...   
470464  public BackupFileSet listRawBackup(final boole...   
470465  public CountingIdlingResource(String resourceN...   
470466  public ImageReuseInfo create(String thisSize){...   
470467  public static void sync(Address address,int si...   
470468  public MonthDateFormat(Locale locale){\n  this...   
470469  public void testConnectorSecuritySettingsSSL_a...   
470470  public synchronized void add(double x,double y...   
470471  public void fatalError(SAXParseException excep...   
470472  @Override public void run(){\n  amIActive=true...   
470473  public static void addMoreComponents(Container...   
470474  public static CCProgressTimer progress(CCTextu...   
470475  protected EntityMappingModelImpl(){\n  super()...   
470476  public MatchResult match(){\n  if (!matchSucce...   
470477  @Override public void dispatch(IEvent event){\...   
470478  JComboBox createMouthComboBox(){\n  JComboBox ...   
470479  public double leverageForRule(AprioriItemSet p...   
470480  public RdKNNNode(int capacity,boolean isLeaf){...   
470481  private void adaptGridViewHeight(){\n  if (gri...   
470482  protected void validateOnStatus(){\n  if (Comm...   
470483  public Optional<Boolean> eagerCheck(){\n  retu...   
470484  public static NewPlaylistFragment newInstance(...   
470485  @DSSink({DSSinkKind.LOG}) @DSGenerator(tool_na...   

                                                       nl  
0       Tears down the fixture, for example, close a n...  
1       javax.net.ssl.SSLEngine#unwrap(ByteBuffer src,...  
2       Makes an instance for the given value. This ma...  
3       Returns the "size" of 

In [5]:
test_data.dropna()
test_data

code  \
0      public static String unEscapeString(String str...   
1      public void checkNextPoissonConsistency(double...   
2      public DefaultJobRowBuilder(Function<Map<JobFi...   
3      protected final boolean handleAllocNode(AllocN...   
4      @Override protected FieldConfigBase createCopy...   
5      public void handleEntryExpiredSA(EntryExpiredB...   
6      public static SM_SYSTEM_MESSAGE STR_EXTRACT_GA...   
7      public void toggle(Animation animIn,Animation ...   
8      private boolean isInSameEvolutionChain(Pokemon...   
9      public static SM_SYSTEM_MESSAGE STR_SKILL_SUCC...   
10     public PhotosGetUploadServerQuery(VkApiClient ...   
11     public ChangeReport onEquipmentUnitAdd(final E...   
12     private void requestNewPhotosOrders(Context c,...   
13     public static void picture(double x,double y,S...   
14     public VisualTable(Visualization vis,String gr...   
15     public boolean isCritical(){\n  return false;\...   
16     public static DataTag buildCreateBasicDataTag(...   
17     protected void updateRowCount(){\n  int maxrow...   
18     public boolean isSelected(){\n  ClusterViewer ...   
19     public int hashCode(){\n  return (int)(Connect...   
20     protected VideoRemoveTagQuery videoId(int valu...   
21     public static void cover(String dest,int w,int...   
22     public Bindings add(String property,JRadioButt...   
23     public void cancelAlarm(Context context){\n  i...   
24     public static SM_SYSTEM_MESSAGE STR_SKILL_SUCC...   
25     public static <T>T findValueOfType(Collection<...   
26     private static long writeLogSegment(Distribute...   
27     @Override public void characters(char[] ch,int...   
28     protected boolean runTestsOnEdt(){\n  return t...   
29     @Override public Histogram histogram(){\n  ret...   
...                                                  ...   
58781  public static String returnWindowsFileAppropri...   
58782  public synchronized boolean addMacro(int macro...   
58783  public <T>Future execute(int retries,int inter...   
58784  public final int yystate(){\n  return zzLexica...   
58785  protected Expanded doExpand(Record record,long...   
58786  public void pow(final double a,final double[] ...   
58787  @PostConstruct public void init(){\n  listener...   
58788  public static int recordSize(Schema sch){\n  i...   
58789  public void outputOrigin(){\n  out.println("Af...   
58790  public static void d(String tag,String msg){\n...   
58791  public Record verify(List<DataType> values) th...   
58792  public void showEmpty(Drawable emptyImageDrawa...   
58793  @Override public void processingInstruction(St...   
58794  public void goToNextColor(){\n  setColorIndex(...   
58795  public JSONObject(Object bean){\n  this();\n  ...   
58796  public static void export(String type,OutputSt...   
58797  public PhotosGetOwnerPhotoUploadServerQuery ow...   
58798  public NewsfeedSaveListQuery noReposts(Boolean...   
58799  public byte[] externalize(){\n  byte[] options...   
58800  private int parseParameter(String parameter,St...   
58801  public boolean hasNavigtionBar(){\n  return mH...   
58802  public static Predicate<ApiFilter> isNonAggreg...   
58803  public VideoDeleteQuery targetId(Integer value...   
58804  public AudioSearchQuery(VkApiClient client,Use...   
58805  public static String base64ToString(final Stri...   
58806                          public void pause(){\n}\n   
58807  public Vector process(AudioPreProcessor in) th...   
58808  @Override public DimensionColumnDataChunk[] re...   
58809  public boolean acceptsParent(@NotNull NlCompon...   
58810  public boolean contains(ChangeModifiers modifi...   

                                                      nl  
0      Unescape <code>charToEscape</code> in the stri...  
1      Verifies that nextPoisson(mean) generates an e...  
2      Builds a factory for generating JobRows with a...  
3      Propagates new points-to information of node s...  
4                           Creates 

In [6]:
# Make data a np.array
train = train_data.values
test = test_data.values

In [7]:
# Build X and y
y_train = train[:, 1:]
X_train = train[:, 0]
y_test = test[:, 1:]
X_test = test[:, 0]

In [8]:
X_train

array(['protected void tearDown(){\n}\n',
       '@KnownFailure("Fixed on DonutBurger, Wrong Exception thrown") public void test_unwrap_ByteBuffer$ByteBuffer_02(){\n  String host="new host";\n  int port=8080;\n  ByteBuffer bbs=ByteBuffer.allocate(10);\n  ByteBuffer bbR=ByteBuffer.allocate(100).asReadOnlyBuffer();\n  ByteBuffer[] bbA={bbR,ByteBuffer.allocate(10),ByteBuffer.allocate(100)};\n  SSLEngine sse=getEngine(host,port);\n  sse.setUseClientMode(true);\n  try {\n    sse.unwrap(bbs,bbA);\n    fail("ReadOnlyBufferException wasn\'t thrown");\n  }\n catch (  ReadOnlyBufferException iobe) {\n  }\ncatch (  Exception e) {\n    fail(e + " was thrown instead of ReadOnlyBufferException");\n  }\n}\n',
       'public static CstFloat make(int bits){\n  return new CstFloat(bits);\n}\n',
       ...,
       'public Optional<Boolean> eagerCheck(){\n  return Optional.ofNullable(this.eagerCheck);\n}\n',
       'public static NewPlaylistFragment newInstance(Song song){\n  NewPlaylistFragment fragment=

In [9]:
y_train

array([[ 'Tears down the fixture, for example, close a network connection. This method is called after a test is executed.'],
       [ 'javax.net.ssl.SSLEngine#unwrap(ByteBuffer src, ByteBuffer[] dsts) ReadOnlyBufferException should be thrown.'],
       [ 'Makes an instance for the given value. This may (but does not necessarily) return an already-allocated instance.'],
       ..., 
       ['whether check errors as more as possible'],
       [ 'Creates a new instance of the New Playlist dialog fragment to create a new playlist and add a song to it.'],
       ['Report the current cursor location in its window.']], dtype=object)

In [11]:
data = np.concatenate((X_train,y_train[:,0]),axis=0)
data_test = np.concatenate((X_test,y_test[:,0]),axis=0)
# vocabs = sorted(list(set(np.concatenate((data,data_test),axis=0))))
# vocab_to_int = dict((c, i) for i, c in enumerate(vocabs))   #Vectorize the text
# int_to_vocab = dict((i, c) for i, c in enumerate(vocabs))

In [15]:
%%time
import nltk
import time

start=time.time()
Chracterlist = []
i = 0
for s in data:
    i = i+1
    Chracterlist.extend(nltk.word_tokenize(s))
    if i % 100000 == 0:
        print('----------------------------------------')
        print('Pieces of data: %s'%(i))
        print('The length of List: %s'%(len(Chracterlist)))
        end=time.time()
        print('Running time: %s Seconds'%(end-start))

----------------------------------------
Pieces of data: 100000
The length of List: 8181917
Running time: 54.234426975250244 Seconds
----------------------------------------
Pieces of data: 200000
The length of List: 16410936
Running time: 109.1193470954895 Seconds
----------------------------------------
Pieces of data: 300000
The length of List: 24654664
Running time: 167.07970690727234 Seconds
----------------------------------------
Pieces of data: 400000
The length of List: 32899786
Running time: 221.4487910270691 Seconds
----------------------------------------
Pieces of data: 500000
The length of List: 39111610
Running time: 420.93442606925964 Seconds
----------------------------------------
Pieces of data: 600000
The length of List: 40927050
Running time: 997.1542890071869 Seconds
----------------------------------------
Pieces of data: 700000
The length of List: 42730685
Running time: 1243.7764990329742 Seconds
----------------------------------------
Pieces of data: 800000
Th

In [16]:
vocabs = sorted(list(set(Chracterlist)))
vocab_to_int = dict((c, i) for i, c in enumerate(vocabs))   #Vectorize the text
int_to_vocab = dict((i, c) for i, c in enumerate(vocabs))

In [18]:
len(vocabs)

1875004

In [154]:
testa = np.array([[]], dtype=np.int32)
testb = np.array([1,2,3,4])
testc = np.array([2,3,4,5])
testd = np.array([1,2,3])

In [155]:
testa = np.vstack((testb, testc))

In [156]:
testa = np.vstack((testa, testc))

In [157]:
testa

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [2, 3, 4, 5]])

In [158]:
testa.shape

(3, 4)

In [163]:
for t in testa:
    t = np.pad(t, (6,0), 'constant')
    print(t)

[0 0 0 0 0 0 1 2 3 4]
[0 0 0 0 0 0 2 3 4 5]
[0 0 0 0 0 0 2 3 4 5]


In [165]:
testa[0].shape[0]

4

In [166]:
testa[0][:4]

array([1, 2, 3, 4])

In [49]:
testd = np.array([testd])

In [124]:
f = []
f0 = [0,1,2]
f1 = [1, 1, 1]
f2 = [4,5,6]

features = [f0, f1, f2]

In [167]:
encoded_s = np.array([vocab_to_int[c] for c in nltk.word_tokenize(data[0])], dtype=np.int32)

In [170]:
encoded_s.shape[0]

7

In [171]:
if encoded_s.shape[0]<50:
    l = encoded_s.shape[0]
    encoded_s = np.pad(encoded_s, (50-l,0), 'constant')

In [173]:
encoded_s.shape

(50,)

In [174]:
if encoded_s.shape[0]>=3:
    encoded_s = encoded_s[:3]

In [175]:
encoded_s

array([0, 0, 0], dtype=int32)

In [190]:
test = np.empty([50])

In [191]:
test.shape

(50,)

In [187]:
test[0]

array([], dtype=float64)

In [ ]:
%%time
start = time.time()
encoded = np.empty([50])
i = 0
for s in data:
    i = i+1
    encoded_s = np.array([vocab_to_int[c] for c in nltk.word_tokenize(s)], dtype=np.int32)
    if encoded_s.shape[0]<50:
        l = encoded_s.shape[0]
        encoded_s = np.pad(encoded_s, (50-l,0), 'constant')
    else:
        encoded_s = encoded_s[:50]
        
    encoded = np.vstack((encoded, encoded_s))    
    if i % 100000 == 0:
        print('----------------------------------------')
        print('Pieces of data Processed: %s'%(i))
        print('The Shape of Encoded Array: %s'% (encoded.shape,))
        end=time.time()
        print('Running time: %s Seconds'%(end-start))

----------------------------------------
Pieces of data Processed: 100000
The Shape of Encoded Array: (100001, 50)
Running time: 858.5675051212311 Seconds
----------------------------------------
Pieces of data Processed: 200000
The Shape of Encoded Array: (200001, 50)
Running time: 3207.433900117874 Seconds
----------------------------------------
Pieces of data Processed: 300000
The Shape of Encoded Array: (300001, 50)
Running time: 6953.629225969315 Seconds
----------------------------------------
Pieces of data Processed: 400000
The Shape of Encoded Array: (400001, 50)
Running time: 16118.49967098236 Seconds
----------------------------------------
Pieces of data Processed: 500000
The Shape of Encoded Array: (500001, 50)
Running time: 31126.15179014206 Seconds


In [214]:
encoded.shape

(156896, 50)

In [9]:
x = X_train
for i in x:
    i = i.lower()
    
y = y_train[0]
for i in y:
    i = i.lower()
    
xt = X_test
for i in x:
    i = i.lower()
    
yt = y_test[0]
for i in y:
    i = i.lower()

In [14]:
encoded = np.array([vocab_to_int[c] for c in data], dtype=np.int32)

In [15]:
encoded.shape

(940972,)

In [16]:
Xencoded = encoded[0:470486]
Yencoded = encoded[470486:940972]

In [17]:
Xencoded = np.reshape(Xencoded, (-1,1))

In [18]:
encodedt = np.array([vocab_to_int[c] for c in data_test], dtype=np.int32)

In [19]:
XTencoded = encoded[0:20]
YTencoded = encoded[20:encodedt.shape[0]]

In [20]:
XTencoded = np.reshape(XTencoded, (-1,1))

In [21]:
# Xencoded = np.array([Xencoded]).transpose()
# Xtest[:,0] = Xencoded

In [22]:
# Import Tensorflow
import tensorflow as tf

/anaconda3/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)


In [23]:
# Number of pieces of data in training
n_code = Xencoded.shape[1]

# Neurons
n_neurons_1 = 1024
n_neurons_2 = 512
n_neurons_3 = 256
n_neurons_4 = 128

In [24]:
# Session
net = tf.InteractiveSession()

In [25]:
# Placeholder
X = tf.placeholder(dtype=tf.float32, shape=[None, n_code])
Y = tf.placeholder(dtype=tf.float32, shape=[None])

In [26]:
# Initializers
sigma = 1
weight_initializer = tf.variance_scaling_initializer(mode="fan_avg", distribution="uniform", scale=sigma)
bias_initializer = tf.zeros_initializer()

In [27]:
# Hidden weights
W_hidden_1 = tf.Variable(weight_initializer([n_code, n_neurons_1]))
bias_hidden_1 = tf.Variable(bias_initializer([n_neurons_1]))
W_hidden_2 = tf.Variable(weight_initializer([n_neurons_1, n_neurons_2]))
bias_hidden_2 = tf.Variable(bias_initializer([n_neurons_2]))
W_hidden_3 = tf.Variable(weight_initializer([n_neurons_2, n_neurons_3]))
bias_hidden_3 = tf.Variable(bias_initializer([n_neurons_3]))
W_hidden_4 = tf.Variable(weight_initializer([n_neurons_3, n_neurons_4]))
bias_hidden_4 = tf.Variable(bias_initializer([n_neurons_4]))

In [28]:
# Output weights
W_out = tf.Variable(weight_initializer([n_neurons_4, 1]))
bias_out = tf.Variable(bias_initializer([1]))

In [29]:
# Hidden layer
hidden_1 = tf.nn.relu(tf.add(tf.matmul(X, W_hidden_1), bias_hidden_1))
hidden_2 = tf.nn.relu(tf.add(tf.matmul(hidden_1, W_hidden_2), bias_hidden_2))
hidden_3 = tf.nn.relu(tf.add(tf.matmul(hidden_2, W_hidden_3), bias_hidden_3))
hidden_4 = tf.nn.relu(tf.add(tf.matmul(hidden_3, W_hidden_4), bias_hidden_4))

In [30]:
# Output layer (transpose!)
out = tf.transpose(tf.add(tf.matmul(hidden_4, W_out), bias_out))

In [31]:
# Cost function
mse = tf.reduce_mean(tf.squared_difference(out, Y))

In [32]:
# Optimizer
# Adam
opt = tf.train.AdamOptimizer().minimize(mse)

In [33]:
# Init
net.run(tf.global_variables_initializer())

In [34]:
init = tf.global_variables_initializer()

In [35]:
# Fit neural net
batch_size = 256
mse_train = []
mse_test = []

In [39]:
epochs = 50 #number of iterations or training cycles

saver = tf.train.Saver(max_to_keep=4)
with tf.Session() as sess:
    init.run()
    for e in range(epochs):
        sess.run(opt, feed_dict={X: Xencoded, Y: Yencoded})
        if e % 10 == 0:
            print("-----------------------")
            loss = mse.eval(feed_dict={X: Xencoded, Y: Yencoded})
            print(e, "\tMSE:", loss)
            print("----------save the model")
            saver.save(sess, "model/my-model", global_step=e)   
    y_pred = sess.run(out, feed_dict={X: XTencoded})

-----------------------
0 	MSE: 3.82309e+10
----------save the model
-----------------------
10 	MSE: 2.30321e+10
----------save the model
-----------------------
20 	MSE: 2.24954e+10
----------save the model
-----------------------
30 	MSE: 2.21959e+10
----------save the model
-----------------------
40 	MSE: 2.21021e+10
----------save the model


In [40]:
sc_test = 'public static CstFloat make(int bits){\n  return new CstFloat(bits);\n}\n'
source_code_test = np.array([sc_test])
encoded_code_test = np.array([vocab_to_int[c] for c in source_code_test], dtype=np.int32)
encoded_code_test = np.reshape(encoded_code_test, (-1,1))

In [42]:
def load_model(x_to_predict):
    with tf.Session() as sess:
        saver = tf.train.import_meta_graph('model/my-model-40.meta')
        saver.restore(sess, tf.train.latest_checkpoint("model/"))
        y_pred = sess.run(out, feed_dict={X: x_to_predict})
        print(y_pred)
        return y_pred

In [44]:
y_pred = load_model(encoded_code_test)

INFO:tensorflow:Restoring parameters from model/my-model-40
[[ 239055.25]]


In [53]:
y_pred = np.array([int(y_pred[0][0])])

In [54]:
y_pred = [int_to_vocab[c] for c in y_pred]

In [56]:
y_pred

['Normalize the character sequence <code>src</code> according to the normalization method <code>form</code>.']

In [59]:
def CommentGenerate(source_code):
    source_code = np.array([source_code])
    encoded_sc = np.array([vocab_to_int[c] for c in source_code], dtype=np.int32)
    encoded_sc = np.reshape(encoded_sc, (-1,1))
    y_pred = load_model(encoded_sc)
    encoded_pred = np.array([int(y_pred[0][0])])
    comment_pred = [int_to_vocab[c] for c in encoded_pred]
    return comment_pred

In [60]:
y_pred_comment = CommentGenerate(sc_test)

INFO:tensorflow:Restoring parameters from model/my-model-40
[[ 239055.25]]


In [61]:
y_pred_comment

['Normalize the character sequence <code>src</code> according to the normalization method <code>form</code>.']

In [ ]:
# CommentGenerate('public static CstFloat make(int bits){\n  return new CstFloat(bits);\n}\n')

In [ ]:
# corpus = []
# w2v_model = Word2Vec(corpus, size=128, window=5, min_count=5, workers=4)

In [211]:
vocabs

['\x1b',
 '!',
 '#',
 '$',
 '%',
 '&',
 "'",
 "''",
 "''A",
 "''AS",
 "''B",
 "''Router",
 "''\\",
 "''\\\\",
 "''\\\\N",
 "''\\\\\\\\",
 "''\\\\\\\\\\\\",
 "''best",
 "''is",
 "''quotes",
 "''router",
 "''strange",
 "''string",
 "'*",
 "'**",
 "'*+-/=",
 "'*Repo*",
 "'*Report",
 "'*virtual*",
 "'+",
 "'+'|'-",
 "'+MySQL",
 "'+id+",
 "',0",
 "',1",
 "',1488",
 "',2",
 "',3",
 "',5",
 "',50",
 "',6",
 "',8",
 "'-",
 "'-'+",
 "'-//Sun",
 "'-1",
 "'-A",
 "'-C",
 "'-Dx",
 "'-Dx=",
 "'-Dx=v",
 "'-FF",
 "'-I",
 "'-K",
 "'-P",
 "'-W",
 "'-X",
 "'-appname",
 "'-classification",
 "'-classifications/-p",
 "'-classpath",
 "'-closeto'.\\n",
 "'-configuration",
 "'-contextroot",
 "'-cp",
 "'-escaped",
 "'-file",
 "'-find'.\\n",
 "'-h",
 "'-index",
 "'-k",
 "'-no-predictions",
 "'-no-replacement",
 "'-not-numeric-class",
 "'-p",
 "'-remove'.\\n",
 "'-replace",
 "'-s",
 "'-separated",
 "'-size",
 "'-split-percentage",
 "'-t",
 "'-u",
 "'-updateMovies",
 "'-view",
 "'-x",
 "'.",
 "'.+",
 "'..",
 "'..\

In [210]:
vocabs.to_csv('vocabs',encoding='utf-8')

AttributeError: 'list' object has no attribute 'to_csv'

In [212]:
data_vocabs=pd.DataFrame(data=vocabs)#
data_vocabs.to_csv('vocabs.csv',encoding='gbk')

In [213]:
vocabs

['\x1b',
 '!',
 '#',
 '$',
 '%',
 '&',
 "'",
 "''",
 "''A",
 "''AS",
 "''B",
 "''Router",
 "''\\",
 "''\\\\",
 "''\\\\N",
 "''\\\\\\\\",
 "''\\\\\\\\\\\\",
 "''best",
 "''is",
 "''quotes",
 "''router",
 "''strange",
 "''string",
 "'*",
 "'**",
 "'*+-/=",
 "'*Repo*",
 "'*Report",
 "'*virtual*",
 "'+",
 "'+'|'-",
 "'+MySQL",
 "'+id+",
 "',0",
 "',1",
 "',1488",
 "',2",
 "',3",
 "',5",
 "',50",
 "',6",
 "',8",
 "'-",
 "'-'+",
 "'-//Sun",
 "'-1",
 "'-A",
 "'-C",
 "'-Dx",
 "'-Dx=",
 "'-Dx=v",
 "'-FF",
 "'-I",
 "'-K",
 "'-P",
 "'-W",
 "'-X",
 "'-appname",
 "'-classification",
 "'-classifications/-p",
 "'-classpath",
 "'-closeto'.\\n",
 "'-configuration",
 "'-contextroot",
 "'-cp",
 "'-escaped",
 "'-file",
 "'-find'.\\n",
 "'-h",
 "'-index",
 "'-k",
 "'-no-predictions",
 "'-no-replacement",
 "'-not-numeric-class",
 "'-p",
 "'-remove'.\\n",
 "'-replace",
 "'-s",
 "'-separated",
 "'-size",
 "'-split-percentage",
 "'-t",
 "'-u",
 "'-updateMovies",
 "'-view",
 "'-x",
 "'.",
 "'.+",
 "'..",
 "'..\